defaultEntryPoints = ["http", "https"]
[web]
address = ":8080"
  [web.auth.basic]
  users = ["admin:$apr1$RpGlPqCc$M.uKBXVjGHPg3uRsGDM6E."]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
[acme]
  email = "charles.cantrell@me.com"
  storage = "acme.json"
  acmeLogging = true
  entryPoint = "https"
  onHostRule = true
  onDemand = false
  # caServer = "https://acme-staging.api.letsencrypt.org/directory"
[docker]
  domain = "pinkhippos.io"
